soumyasnowflake:
  outputs:
    dev:
      account: WKLPRPS-CP26967
      database: AIRBNB_DBT
      password: Shivanshkaushik@123
      role: ACCOUNTADMIN
      schema: dbt_target
      threads: 1
      type: snowflake
      user: SOUMYAWIZARD9
      warehouse: MEDIUM_WH
  target: dev
